spring.application.name=Project
#서버 포트 설정
server.port=8282

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=SCOTT
spring.datasource.password=${JDBC_PASSWORD}

#서의 코드가 수정됭면 자동으로 서버가 리로드 된다
#운영서버 리로드  
spring.devtools.restart.enabled=true  
#개발서버 리로드  
spring.devtools.livereload.enabled=true

#콘솔 출력 형식도 시간까지 보이게 추가
logging.level.org.springframework=info
logging.level.kr.or.oti.project=debug
logging.pattern.console=%d{HH:mm:ss} %-5level [%logger{36}] - %msg%n

# 수정
#MyBatis 설정
# XML 매퍼 파일 위치 (resources/mapper 폴더 아래 xml들을 인식)
mybatis.mapper-locations=classpath:mapper/**/*.xml
# DTO/VO 클래스 패키지 (매퍼 XML에서 패키지 없이 클래스명만 쓸 수 있게 해줌)
mybatis.type-aliases-package=kr.or.oti.project.domain
# DB 컬럼(스네이크 케이스) <-> 자바 필드(카멜 케이스) 자동 매핑
# mybatis.configuration.map-underscore-to-camel-case=true
# 마이바티스 로그 확인용 (개발 중 SQL 실행 로그 보기)
logging.level.kr.or.oti.project.mapper=trace

#일반 로그인 스프링 부트 기본설정(30분) -> 20분 변경
server.servlet.session.timeout=20m